### ISSUE TITLE
page setting

### ISSUE THREAD

**Issue by superminji** [LifeAlgorithm/VitalSourcePrinter#2]
my ebook page number is like 1-1 (ch1, page 1) 5-34(ch5 page 34)
so I tried to set the first page 1-1 and last page 5-1 but IDLE doesn't recognize the number :(

**Comment by LifeAlgorithm** [comment]
The numbers are not being recognized because the input is validated to be an integer. I can make a separate script for chapter pages to accept string input. I imagine it would work like this -> 1) Ask user how many chapters. 2) For each chapter, get count of pages. 3) Iterate over every combination of a chapter-page, and print. I can write a script for you.

**Comment by superminji** [comment]
Thank you so much! where can I find the script?

**Comment by LifeAlgorithm** [comment]
Just uploaded it as "VitalSourcePrinter_ChapPage.py". Are there any zero chapter pages? Like 0-1 or 5-0? I have the default set to 1 as the minimum.  But anyway, let me know if it works

**Comment by superminji** [comment]
<img width="427" alt="default" src="https://cloud.githubusercontent.com/assets/25260882/22343744/3a70d53c-e3c7-11e6-81c7-c7f3dd463496.PNG">

no there are not any zero chapter pages, but it doesn't work :'(

**Comment by LifeAlgorithm** [comment]
Oops, typo in the variable name. Just fixed, try again.

**Comment by superminji** [comment]
It works ! Thank you so much! xD
